version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  backend:
    build: ./backend
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword123!
      - DB_NAME=appdb
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - PORT=3000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  db_data:
